### ISSUE TITLE
Design logo

### ISSUE THREAD

**Issue by domoritz** [cmudig/cmudig.github.io#1]

**Comment by cabreraalex** [comment]
Rough logo thought -> can play around with which visualizations to show, but they can be relevant to the group, like group commit heatmap, website hits, people -> venues/orgs. <img width="813" alt="Screen Shot 2019-11-08 at 11 19 34 AM" src="https://user-images.githubusercontent.com/4563691/68493012-a5f5aa80-0219-11ea-8f46-7d05b9a12e82.png">

**Comment by adamperer** [comment]
That's clever... if it can be pulled off without being too overwhelming.

My initial half-baked idea was to scrape vectors of shovels from Quickdraw ( https://quickdraw.withgoogle.com/data/shovel ), pixelate them a bit into squarified regions, and then animate between them.  But doesn't have much "data".  I guess we could color the pixelated regions by how often those regions are used in Quickdraw.  *shrug*.

**Comment by cabreraalex** [comment]
Oooo that's really creative, could be awesome.

Yeah the visualizations would have to be really simple for it to not be too much

**Comment by domoritz** [comment]
@ldegreef had the idea to take Scottie and make it dig. https://www.cmu.edu/brand/downloads/index.html

**Comment by domoritz** [comment]
I also like the shovel idea!

**Comment by cabreraalex** [comment]
<img width="940" alt="Screen Shot 2019-11-08 at 11 47 32 AM" src="https://user-images.githubusercontent.com/4563691/68495140-98daba80-021d-11ea-86e0-8bef9420ca78.png">

_the graphs are supposed to be dirt ;)_

**Comment by domoritz** [comment]
Here is @ldegreef's concept sketch

<img width="541" alt="Screen Shot 2019-11-08 at 21 16 05" src="https://user-images.githubusercontent.com/589034/68523366-0f52d900-026d-11ea-8c28-246293781324.png">

**Comment by adamperer** [comment]
Thanks @ldegreef for this awesome sketch.  I really like the concept.  If we wanted to go overboard, we could have the dirt animate into an empty DIG text header that fills up with the black dirt... but that is probably 100% unnecessary :)

**Comment by adamperer** [comment]
@domoritz @ldegreef Would it be helpful to have a student come up with a final draft of this sketch?  I think one of the students I'm working with could do a great job of this.

**Comment by domoritz** [comment]
I think @ldegreef wanted to change some details about the scarf. @ldegreef, do you want to refine the draft over the break before handing it off?

**Comment by domoritz** [comment]
Done in https://github.com/cmudig/logo. Let's move any feedback and to issues over there.
