### ISSUE TITLE
Add info about DIG hosting a VIS satellite event

### ISSUE THREAD

**Issue by adamperer** [cmudig/cmudig.github.io#108]
> - Satellites are now listed on the VIS website: http://ieeevis.org/year/2021/info/satellite. We would like all satellites to set up their own website outlining their satellite and the local program.  These sites will be linked in this list.

**Comment by adamperer** [comment]
GHC 4405 reserved for opening and closing sessions:
8:30am-3pm on Tuesday October 26.  and
12pm - 3pm on Friday, October 29

**Comment by domoritz** [comment]
Done in #109
