### ISSUE TITLE
Add alumni section to team

### ISSUE THREAD

**Issue by adamperer** [cmudig/cmudig.github.io#16]
several students have graduated

**Comment by domoritz** [comment]
We could add a Boolean alumni field to the person or change their position to alumni. In the latter we lose the information about what someone did, which I think is fine. What do you think?

**Comment by adamperer** [comment]
It would be nice to distinguish PhD alumni from undergrad alumni, for example, so I think I prefer the boolean option.

**Comment by domoritz** [comment]
Done in https://github.com/cmudig/cmudig.github.io/pull/17. Feel free to merge and mark people as alumni.
