### ISSUE TITLE
Font changes on small screen sizes

### ISSUE THREAD

**Issue by venkatesh-sivaraman** [cmudig/cmudig.github.io#59]
Big screen:
<img width="1153" alt="Screen Shot 2021-02-26 at 1 46 37 PM" src="https://user-images.githubusercontent.com/13065028/109341930-20947000-7839-11eb-9b00-17c3dd615be2.png">
Small screen:
<img width="571" alt="Screen Shot 2021-02-26 at 1 46 54 PM" src="https://user-images.githubusercontent.com/13065028/109341943-268a5100-7839-11eb-8e0c-5722ebf641b3.png">

The issue appears on Safari and Firefox for macOS (Catalina) and Safari for iOS 14.

**Comment by domoritz** [comment]
Interesting. The problem has been there from the beginning: https://github.com/cmudig/cmudig.github.io/blob/master/styles.scss#L16. I think my idea was to use the system font on small screens but that's not really all that much better.
