### ISSUE TITLE
Specify publication filters with URL parameters

### ISSUE THREAD

**Issue by adamperer** [cmudig/cmudig.github.io#71]
Could we do something like:
https://dig.cmu.edu/publications?author="Adam Perer" to filter the papers?

I'd like to be able to link to a filtered subset of all of our papers

**Comment by domoritz** [comment]
That would be nice. The code for the search isn't too bad if you want to take a stab. It's at https://github.com/cmudig/cmudig.github.io/blob/master/_includes/pubfilter.js.

**Comment by domoritz** [comment]
I'm adding support for `#authors=Adam Perer` with support for any search field.

**Comment by domoritz** [comment]
https://dig.cmu.edu/publications#authors=Adam%20Perer

**Comment by adamperer** [comment]
Thanks Dominik!  I can now use this link on my personal homepage and not have to maintain two separate DBs!
