### ISSUE TITLE
Update the team page

### ISSUE THREAD

**Issue by domoritz** [cmudig/cmudig.github.io#98]
Move people to alumni who are not actively working in the group anymore.

**Comment by adamperer** [comment]
moved those who are fully not active.  there will be more alumni in a few weeks after the summer ends, so will keep this open for now.  

we should consider making alumni a bit more visually prominent than they are now.

**Comment by adamperer** [comment]
I took a stab at this in the [team branch](https://github.com/cmudig/cmudig.github.io/tree/team)
![image](https://user-images.githubusercontent.com/1194662/127532487-eb43c627-1a31-4daa-9ea4-00b843f74774.png)

**Comment by domoritz** [comment]
Good idea. I'd maybe not group the alumni so we can sort them by time instead. What do you think?

**Comment by adamperer** [comment]
@domoritz I originally designed it similar to that, but there wasn't enough space below the images to list their role without major line breaks, so it looked bad.   Would you prefer as-is, or leave out the role and just have names+images, sorted by time?

**Comment by domoritz** [comment]
I see. We could try to make the text smaller but I can imagine that it's still tight.

The role for alumni isn't as important imo so we could omit it. Good idea!
